export const getEnvironment = () => {
	const {
		TOOVER_API_BASE_URL,
		TOOVER_ENV,
		TOOVER_FIREBASE_API_KEY,
		TOOVER_FIREBASE_APP_ID,
		TOOVER_FIREBASE_PROJECT_ID,
		TOOVER_FIREBASE_AUTH_DOMAIN,
		TOOVER_FIREBASE_MESSAGING_SENDER_ID,
		TOOVER_FIREBASE_STORAGE_BUCKET,
	} = import.meta.env;
	return {
		env: TOOVER_ENV,
		api: TOOVER_API_BASE_URL,
		firebase: {
			apiKey: TOOVER_FIREBASE_API_KEY,
			appId: TOOVER_FIREBASE_APP_ID,
			projectId: TOOVER_FIREBASE_PROJECT_ID,
			authDomain: TOOVER_FIREBASE_AUTH_DOMAIN,
			messagingSenderId: TOOVER_FIREBASE_MESSAGING_SENDER_ID,
			storageBucket: TOOVER_FIREBASE_STORAGE_BUCKET,
		},
	};
};
